name: Terraform Static Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-static-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Run tfsec for static security analysis
        uses: aquasecurity/tfsec-action@v1
        with:
          terraform_dir: ./infrastructure
